r"""Stage refs-goblin-d1stand-0815: four STANDING FULL BODIES, all on real ground.

WHAT PROBLEM THIS CLOSES. d1 seed s1 held exactly ONE sound standing tile, so
every set built from it was one distinct picture poured into four slots and the
sampler's content dedup would correctly have drawn four frames instead of
sixteen. This set is four DIFFERENT standing full bodies of the same design,
generated by ep2-b04-standing-views-0815 with that one tile as the IP-Adapter
anchor, so the design carries and the slots are genuinely four.

WHY ALL FOUR COME FROM ROUND r0 AND NOTHING ELSE. r0 is the round whose
reference was the UNPADDED standing tile (sha256 9526882e.., byte-identical to
refs-goblin-d1-0815 slot s2). It is the only one of the four rounds whose frames
came back in a PLACE. Rounds r1, r2 and r3 were conditioned on the same tile
white-padded to 75%, 55% and 40%, and 11 of their 12 frames came back on blank
white with at most a tuft of grass under the boots -- even though the prompt
said "standing in sunlit grass, pale sky above him" and the negative carried
`white background, simple background`. So the blank paper is imposed by the
REFERENCE's white field and no wording overrides it. Taking a tile from r1/r2/r3
would carry that defect straight back into the next set.

THE TRANSFORM, and why there is no white in it anywhere. The harness centre-crops
its reference to a square before the CLIP image processor sees it, which on an
832x1216 portrait would silently eat the skull and the boots -- the figure spans
about 92% of the frame height. So the square is made HERE, deliberately, and the
harness's own crop becomes a no-op:

    832x1216 frame -> resample to 570x832 (LANCZOS)
                   -> paste centred on an 832x832 canvas
                   -> fill the 131 px band on each side with a MIRROR of the
                      adjacent 131 px strip of that same resized frame

Every pixel in the finished tile is a pixel of its own source frame. The side
bands are sky continuing as sky and grass continuing as grass, so the tile is
full-bleed LOCATION edge to edge. This is the deliberate alternative to padding:
the previous sweep bought its margin with a white field and put every conditioned
round on blank paper.

MARGIN IS NOT ADDED, and that is a finding rather than an omission. The margin
ladder was supposed to buy head-to-body ratio. In this run it did not: round r0,
whose reference had NO padding at all, came back at ~5.5 heads -- level with the
padded rounds. Once the ask is STANDING and the wording is ADULT, the proportion
is already there and the margin only costs the location. There is also no way to
add margin to these frames by cropping, because the figure already fills 92% of
the frame height; more margin could only be invented.

Refuses unless each source frame's sha256 is the one published by
ep2-b04-standing-views-0815, and unless the four finished tiles are four distinct
sha256 (which is the whole point of the set).
"""
import hashlib
import os
import sys

from PIL import Image

SRC = r"C:\banyan-farm\goblin-ipa-0812\out-b04-standing-views-0815"
DST = r"C:\banyan-farm\wave-goblin-prep\refs-goblin-d1stand-0815"
PREFIX = "goblin-d1stand"
SIDE = 832

# slot -> (source frame, its published sha256, pose/read)
# Mapping is by CONTENT HASH, never by position: a lane lost a day to an s0/s1
# position mix-up and slot order is not evidence.
SOURCES = [
    (0, "04-the-footnote-ipa-r0-w015-s0.png",
     "f4273d143c0254b31192a728368bc704aa56b1a52a853b3d7d2107b3e97d410e",
     "standing full body, frontal, arms hanging at his sides, weight even, "
     "brown shoes; dry grass foreground and pale blue sky with cloud streaks"),
    (1, "04-the-footnote-ipa-r0-w015-s1.png",
     "652eb336f671b663545f19ccbca126a24015ac46e37f608aab2a724de5bcd47d",
     "standing full body, frontal, arms at his sides, hands slightly forward, "
     "largest and sharpest ears of the four; grass underfoot, sky is a soft "
     "pale glow rather than a drawn sky"),
    (2, "04-the-footnote-ipa-r0-w015-s2.png",
     "e482dfb7e25788ce77a27a0467d630f202d8bd1f3e908cafbc6d5ed782e04ed8",
     "standing full body, frontal, arms at his sides, dark boots, a small "
     "cross-shaped scar on the left brow; flowering meadow and clouded sky"),
    (3, "04-the-footnote-ipa-r0-w015-s3.png",
     "051c5a928e956f817472ad0d03785582d210a9ac9106d2cbcef98fd5e08614ee",
     "standing full body, frontal, arms at his sides; sky, clouds and distant "
     "trees. THE OFF-DESIGN SLOT -- see not_scored below"),
]


def sha(p):
    with open(p, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def main():
    os.makedirs(DST, exist_ok=True)
    out = []
    for slot, name, expect, _pose in SOURCES:
        s = os.path.join(SRC, name)
        h = sha(s)
        if h != expect:
            print("!! %s is not the published frame:\n   got      %s\n"
                  "   expected %s" % (name, h, expect))
            return 2
        img = Image.open(s).convert("RGB")
        if img.size != (832, 1216):
            print("!! %s is %s, expected 832x1216" % (name, img.size))
            return 3

        w = int(round(SIDE * img.width / img.height))        # 570
        band = (SIDE - w) // 2                               # 131
        if band <= 0:
            print("!! %s is not portrait enough to need side bands" % name)
            return 4
        # The right band is sized from what is LEFT OVER, not assumed equal to
        # the left one: 832*832/1216 rounds to 569, so band*2 + w is 831 and a
        # symmetric paste leaves the last column unpainted. It showed up as a
        # BLACK corner on all four tiles the first time this ran, which is
        # exactly what the corner assertion below is for.
        right_w = SIDE - band - w
        small = img.resize((w, SIDE), Image.LANCZOS)
        canvas = Image.new("RGB", (SIDE, SIDE))
        canvas.paste(small, (band, 0))
        # EDGE EXTENSION, not mirroring. The first version mirrored the outer
        # 131 px strip, and on two of the four tiles that strip contained his
        # SLEEVE -- so the finished reference showed a detached fragment of arm
        # floating at the frame edge. A duplicated limb is precisely what
        # `extra limbs` is in the negative to prevent, and putting one in the
        # reference would be asking for it. Stretching the outermost COLUMN
        # instead continues the sky and the grass as flat horizontal bands and
        # cannot duplicate any part of the figure, because that column is
        # background on every frame in this set (asserted below).
        left = small.crop((0, 0, 1, SIDE)).resize((band, SIDE))
        right = small.crop((w - 1, 0, w, SIDE)).resize((right_w, SIDE))
        canvas.paste(left, (0, 0))
        canvas.paste(right, (band + w, 0))

        # The tile must NOT be blank paper at its edges -- that is the defect
        # this whole set exists to avoid, so it is asserted rather than hoped for.
        corners = [canvas.getpixel(p) for p in
                   ((0, 0), (SIDE - 1, 0), (0, SIDE - 1), (SIDE - 1, SIDE - 1))]
        if all(all(c > 246 for c in px) for px in corners):
            print("!! %s came out white in all four corners -- that is the "
                  "blank-paper defect this set exists to avoid" % name)
            return 5
        if any(px == (0, 0, 0) for px in corners):
            print("!! %s has an unpainted BLACK corner %s -- the side bands did "
                  "not cover the canvas" % (name, corners))
            return 7
        # WHETHER THE FIGURE REACHES THE FRAME EDGE IS CHECKED BY EYE, and two
        # failed attempts at automating it are recorded here so the next lane
        # does not spend the same hour:
        #
        #   1. Spread of colour DOWN the edge column, refuse over a threshold.
        #      Wrong: every frame runs bright sky at the top to dark grass at the
        #      bottom, so a large vertical spread IS the location. It refused at
        #      222 on a perfectly good tile. The band reproduces that gradient
        #      correctly anyway, because each row takes its own edge pixel.
        #   2. Compare the outermost column against one 24 px inward, row by row.
        #      Also wrong: grass is high-frequency texture and a 24 px shift
        #      moves whole blades, which reads as 170 on a clean tile.
        #
        # Neither number separates "figure at the edge" from "grass". The picture
        # does, instantly, and this project's own rule is that where a number and
        # the picture disagree the picture wins -- so this is an eye check and the
        # corner assertions above are what stays automated, because those caught a
        # real defect (an unpainted black column) that the eye nearly missed.
        # Verified 2026-08-15: on all four frames the figure stands clear of both
        # side edges, and the outermost column is sky over grass on every row.

        d = os.path.join(DST, "%s-s%d.png" % (PREFIX, slot))
        canvas.save(d)
        out.append((slot, name, h, sha(d), corners))
        print("s%d  <- %s  src %s -> tile %s  corners=%s"
              % (slot, name, h[:12], sha(d)[:12], corners))

    tiles = [o[3] for o in out]
    if len(set(tiles)) != 4:
        print("!! the four tiles are not four distinct pictures -- the sampler "
              "would dedup them and draw fewer than sixteen frames")
        return 6

    with open(os.path.join(DST, "MANIFEST.yaml"), "w", newline="\n") as fh:
        fh.write("# refs-goblin-d1stand-0815 -- four standing full bodies, all "
                 "on real ground.\n")
        fh.write("# Mapping is by CONTENT HASH. Position is not evidence.\n")
        fh.write("set: refs-goblin-d1stand-0815\n")
        fh.write("frozen_on: '2026-08-15'\n")
        fh.write("ref_prefix: %s\n" % PREFIX)
        fh.write("character: goblin\n")
        fh.write("generated_by: ep2-b04-standing-views-0815 (round r0 only)\n")
        fh.write("anchor_reference: goblin-d1std-s0.png\n")
        fh.write("anchor_reference_sha256: "
                 "9526882ef5d6653b22a79d632e7aca6840fc8ea55b88bba207c350f932525b69\n")
        fh.write("anchor_note: >-\n"
                 "  the ONE sound standing tile of d1 seed s1, byte-identical to\n"
                 "  refs-goblin-d1-0815 slot s2, itself cut from\n"
                 "  farm-out/ep2-goblin-design-d1-0814/04-the-footnote-wave1-s1.png\n"
                 "  (sha256 389c7637..) on origin/farm-results-rtx5090\n")
        fh.write("transform: >-\n"
                 "  resample the 832x1216 frame to 570x832 (PIL LANCZOS), paste centred\n"
                 "  on an 832x832 canvas, and fill the 131 px band on each side with a\n"
                 "  mirror of the adjacent strip of that same frame. No white padding\n"
                 "  and no invented content: every pixel is its own frame's pixel.\n")
        fh.write("distinct_slots: %d\n" % len(set(tiles)))
        fh.write("images:\n")
        for (slot, name, src_sha, tile_sha, _c), (_s, _n, _e, pose) in zip(out, SOURCES):
            fh.write("- slot: s%d\n  file: %s-s%d.png\n  sha256: %s\n"
                     "  source_frame: %s\n  source_frame_sha256: %s\n"
                     "  pose: standing\n  pose_detail: %s\n"
                     % (slot, PREFIX, slot, tile_sha, name, src_sha, pose))
        fh.write("not_scored:\n")
        fh.write("- slot: s3\n  why: >-\n"
                 "    OFF-DESIGN. Its ears are small and rounded rather than long and\n"
                 "    pointed and the skin reads grey rather than green, so it is a bald\n"
                 "    old man rather than the design-#1 goblin. It fills the fourth slot\n"
                 "    because the sampler builds slots as {prefix}-s{i} for i in 0..3 and\n"
                 "    refuses on a missing file. SCORE s0, s1 and s2.\n")
        fh.write("alternate_if_proportion_is_wanted_over_location: >-\n"
                 "  04-the-footnote-ipa-r1-w015-s2.png (sha256 3627f58d..) is the leanest\n"
                 "  and tallest figure in the run at roughly 6 heads with excellent ears,\n"
                 "  but it stands on blank white with one tuft of grass. It is NOT in this\n"
                 "  set for that reason and is recorded here so a later lane does not have\n"
                 "  to re-find it.\n")
    print("OK 4 distinct standing tiles ->", DST)
    return 0


if __name__ == "__main__":
    sys.exit(main())
